/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RestaurantIdRouteImport } from './routes/$restaurantId/route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RestaurantIdRouteRoute = RestaurantIdRouteImport.update({
  path: '/$restaurantId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$restaurantId': {
      id: '/$restaurantId'
      path: '/$restaurantId'
      fullPath: '/$restaurantId'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  RestaurantIdRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$restaurantId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$restaurantId": {
      "filePath": "$restaurantId/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
